/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { RatePlan } from "./RatePlan";
import { RatePlanCountArgs } from "./RatePlanCountArgs";
import { RatePlanFindManyArgs } from "./RatePlanFindManyArgs";
import { RatePlanFindUniqueArgs } from "./RatePlanFindUniqueArgs";
import { DeleteRatePlanArgs } from "./DeleteRatePlanArgs";
import { RatePlanService } from "../ratePlan.service";
@graphql.Resolver(() => RatePlan)
export class RatePlanResolverBase {
  constructor(protected readonly service: RatePlanService) {}

  async _ratePlansMeta(
    @graphql.Args() args: RatePlanCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [RatePlan])
  async ratePlans(
    @graphql.Args() args: RatePlanFindManyArgs
  ): Promise<RatePlan[]> {
    return this.service.ratePlans(args);
  }

  @graphql.Query(() => RatePlan, { nullable: true })
  async ratePlan(
    @graphql.Args() args: RatePlanFindUniqueArgs
  ): Promise<RatePlan | null> {
    const result = await this.service.ratePlan(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => RatePlan)
  async deleteRatePlan(
    @graphql.Args() args: DeleteRatePlanArgs
  ): Promise<RatePlan | null> {
    try {
      return await this.service.deleteRatePlan(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
