/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Gds } from "./Gds";
import { GdsCountArgs } from "./GdsCountArgs";
import { GdsFindManyArgs } from "./GdsFindManyArgs";
import { GdsFindUniqueArgs } from "./GdsFindUniqueArgs";
import { DeleteGdsArgs } from "./DeleteGdsArgs";
import { GdsService } from "../gds.service";
@graphql.Resolver(() => Gds)
export class GdsResolverBase {
  constructor(protected readonly service: GdsService) {}

  async _gdsItemsMeta(
    @graphql.Args() args: GdsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Gds])
  async gdsItems(@graphql.Args() args: GdsFindManyArgs): Promise<Gds[]> {
    return this.service.gdsItems(args);
  }

  @graphql.Query(() => Gds, { nullable: true })
  async gds(@graphql.Args() args: GdsFindUniqueArgs): Promise<Gds | null> {
    const result = await this.service.gds(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Gds)
  async deleteGds(@graphql.Args() args: DeleteGdsArgs): Promise<Gds | null> {
    try {
      return await this.service.deleteGds(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
