/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GdsService } from "../gds.service";
import { GdsCreateInput } from "./GdsCreateInput";
import { Gds } from "./Gds";
import { GdsFindManyArgs } from "./GdsFindManyArgs";
import { GdsWhereUniqueInput } from "./GdsWhereUniqueInput";
import { GdsUpdateInput } from "./GdsUpdateInput";

export class GdsControllerBase {
  constructor(protected readonly service: GdsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Gds })
  async createGds(@common.Body() data: GdsCreateInput): Promise<Gds> {
    return await this.service.createGds({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Gds] })
  @ApiNestedQuery(GdsFindManyArgs)
  async gdsItems(@common.Req() request: Request): Promise<Gds[]> {
    const args = plainToClass(GdsFindManyArgs, request.query);
    return this.service.gdsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Gds })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async gds(@common.Param() params: GdsWhereUniqueInput): Promise<Gds | null> {
    const result = await this.service.gds({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Gds })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateGds(
    @common.Param() params: GdsWhereUniqueInput,
    @common.Body() data: GdsUpdateInput
  ): Promise<Gds | null> {
    try {
      return await this.service.updateGds({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Gds })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteGds(
    @common.Param() params: GdsWhereUniqueInput
  ): Promise<Gds | null> {
    try {
      return await this.service.deleteGds({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
