/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RevenueService } from "../revenue.service";
import { RevenueCreateInput } from "./RevenueCreateInput";
import { Revenue } from "./Revenue";
import { RevenueFindManyArgs } from "./RevenueFindManyArgs";
import { RevenueWhereUniqueInput } from "./RevenueWhereUniqueInput";
import { RevenueUpdateInput } from "./RevenueUpdateInput";

export class RevenueControllerBase {
  constructor(protected readonly service: RevenueService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Revenue })
  async createRevenue(
    @common.Body() data: RevenueCreateInput
  ): Promise<Revenue> {
    return await this.service.createRevenue({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Revenue] })
  @ApiNestedQuery(RevenueFindManyArgs)
  async revenues(@common.Req() request: Request): Promise<Revenue[]> {
    const args = plainToClass(RevenueFindManyArgs, request.query);
    return this.service.revenues({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Revenue })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async revenue(
    @common.Param() params: RevenueWhereUniqueInput
  ): Promise<Revenue | null> {
    const result = await this.service.revenue({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Revenue })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRevenue(
    @common.Param() params: RevenueWhereUniqueInput,
    @common.Body() data: RevenueUpdateInput
  ): Promise<Revenue | null> {
    try {
      return await this.service.updateRevenue({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Revenue })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRevenue(
    @common.Param() params: RevenueWhereUniqueInput
  ): Promise<Revenue | null> {
    try {
      return await this.service.deleteRevenue({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
