/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Revenue } from "./Revenue";
import { RevenueCountArgs } from "./RevenueCountArgs";
import { RevenueFindManyArgs } from "./RevenueFindManyArgs";
import { RevenueFindUniqueArgs } from "./RevenueFindUniqueArgs";
import { DeleteRevenueArgs } from "./DeleteRevenueArgs";
import { RevenueService } from "../revenue.service";
@graphql.Resolver(() => Revenue)
export class RevenueResolverBase {
  constructor(protected readonly service: RevenueService) {}

  async _revenuesMeta(
    @graphql.Args() args: RevenueCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Revenue])
  async revenues(
    @graphql.Args() args: RevenueFindManyArgs
  ): Promise<Revenue[]> {
    return this.service.revenues(args);
  }

  @graphql.Query(() => Revenue, { nullable: true })
  async revenue(
    @graphql.Args() args: RevenueFindUniqueArgs
  ): Promise<Revenue | null> {
    const result = await this.service.revenue(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Revenue)
  async deleteRevenue(
    @graphql.Args() args: DeleteRevenueArgs
  ): Promise<Revenue | null> {
    try {
      return await this.service.deleteRevenue(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
