/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Ota } from "./Ota";
import { OtaCountArgs } from "./OtaCountArgs";
import { OtaFindManyArgs } from "./OtaFindManyArgs";
import { OtaFindUniqueArgs } from "./OtaFindUniqueArgs";
import { DeleteOtaArgs } from "./DeleteOtaArgs";
import { OtaService } from "../ota.service";
@graphql.Resolver(() => Ota)
export class OtaResolverBase {
  constructor(protected readonly service: OtaService) {}

  async _otasMeta(
    @graphql.Args() args: OtaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Ota])
  async otas(@graphql.Args() args: OtaFindManyArgs): Promise<Ota[]> {
    return this.service.otas(args);
  }

  @graphql.Query(() => Ota, { nullable: true })
  async ota(@graphql.Args() args: OtaFindUniqueArgs): Promise<Ota | null> {
    const result = await this.service.ota(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Ota)
  async deleteOta(@graphql.Args() args: DeleteOtaArgs): Promise<Ota | null> {
    try {
      return await this.service.deleteOta(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
